/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminiRouteImport } from './routes/termini'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as ChiSiamoRouteImport } from './routes/chi-siamo'
import { Route as CarrelloRouteImport } from './routes/carrello'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OperaSlugRouteImport } from './routes/opera.$slug'

const TerminiRoute = TerminiRouteImport.update({
  id: '/termini',
  path: '/termini',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiSiamoRoute = ChiSiamoRouteImport.update({
  id: '/chi-siamo',
  path: '/chi-siamo',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrelloRoute = CarrelloRouteImport.update({
  id: '/carrello',
  path: '/carrello',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperaSlugRoute = OperaSlugRouteImport.update({
  id: '/opera/$slug',
  path: '/opera/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carrello': typeof CarrelloRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/shop': typeof ShopRoute
  '/termini': typeof TerminiRoute
  '/opera/$slug': typeof OperaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carrello': typeof CarrelloRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/shop': typeof ShopRoute
  '/termini': typeof TerminiRoute
  '/opera/$slug': typeof OperaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carrello': typeof CarrelloRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/shop': typeof ShopRoute
  '/termini': typeof TerminiRoute
  '/opera/$slug': typeof OperaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carrello'
    | '/chi-siamo'
    | '/contatti'
    | '/faq'
    | '/privacy'
    | '/shop'
    | '/termini'
    | '/opera/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carrello'
    | '/chi-siamo'
    | '/contatti'
    | '/faq'
    | '/privacy'
    | '/shop'
    | '/termini'
    | '/opera/$slug'
  id:
    | '__root__'
    | '/'
    | '/carrello'
    | '/chi-siamo'
    | '/contatti'
    | '/faq'
    | '/privacy'
    | '/shop'
    | '/termini'
    | '/opera/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarrelloRoute: typeof CarrelloRoute
  ChiSiamoRoute: typeof ChiSiamoRoute
  ContattiRoute: typeof ContattiRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  ShopRoute: typeof ShopRoute
  TerminiRoute: typeof TerminiRoute
  OperaSlugRoute: typeof OperaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termini': {
      id: '/termini'
      path: '/termini'
      fullPath: '/termini'
      preLoaderRoute: typeof TerminiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chi-siamo': {
      id: '/chi-siamo'
      path: '/chi-siamo'
      fullPath: '/chi-siamo'
      preLoaderRoute: typeof ChiSiamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrello': {
      id: '/carrello'
      path: '/carrello'
      fullPath: '/carrello'
      preLoaderRoute: typeof CarrelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opera/$slug': {
      id: '/opera/$slug'
      path: '/opera/$slug'
      fullPath: '/opera/$slug'
      preLoaderRoute: typeof OperaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarrelloRoute: CarrelloRoute,
  ChiSiamoRoute: ChiSiamoRoute,
  ContattiRoute: ContattiRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  ShopRoute: ShopRoute,
  TerminiRoute: TerminiRoute,
  OperaSlugRoute: OperaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
